# Generated by Django 4.1 on 2022-09-26 09:54

import app.UserManager
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('firstName', models.TextField(blank=True, verbose_name='First Name')),
                ('lastName', models.TextField(blank=True, verbose_name='Last Name')),
                ('is_staff', models.BooleanField(default=True, verbose_name='staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('valid', models.BooleanField(default=True, verbose_name='valid')),
                ('dateJoined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('email',),
            },
            managers=[
                ('objects', app.UserManager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('infected', models.PositiveIntegerField(blank=True, default=0, verbose_name='infected')),
                ('deceased', models.PositiveIntegerField(blank=True, default=0, verbose_name='deceased')),
                ('recovered', models.PositiveIntegerField(blank=True, default=0, verbose_name='recovered')),
                ('quarantined', models.PositiveIntegerField(blank=True, default=0, verbose_name='quarantined')),
                ('tested', models.PositiveIntegerField(blank=True, default=0, verbose_name='tested')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('sourceWeb', models.CharField(blank=True, default='https://apify.com/tugkan/covid-hu', max_length=100, null=True)),
                ('activeInfected', models.PositiveIntegerField(blank=True, default=0, verbose_name='activeInfected')),
            ],
            options={
                'verbose_name': 'CovidData',
                'verbose_name_plural': 'CovidData',
                'ordering': ('date', 'time'),
            },
        ),
        migrations.AddConstraint(
            model_name='coviddata',
            constraint=models.UniqueConstraint(fields=('date', 'time'), name='datetime'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
